version: '3.7'

services:
    productstore:
      restart: always
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - productstoreapp
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/store
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: Duythong1998
      depends_on:
        - mysqldb
      
    mysqldb:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        MYSQL_DATABASE: store
        MYSQL_PASSWORD: Duythong1998
        MYSQL_ROOT_PASSWORD: Duythong1998
      networks:
        - productstoreapp
  
networks:
  productstoreapp:
